# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CCT_cpp <- function(pval) {
    .Call('_SAIGE_CCT_cpp', PACKAGE = 'SAIGE', pval)
}

setGlobalVarsInCPP_LDmat <- function(t_impute_method, t_dosage_zerod_cutoff, t_dosage_zerod_MAC_cutoff, t_missing_cutoff, t_maxMAFLimit, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_max_markers_region, t_outputFile) {
    invisible(.Call('_SAIGE_setGlobalVarsInCPP_LDmat', PACKAGE = 'SAIGE', t_impute_method, t_dosage_zerod_cutoff, t_dosage_zerod_MAC_cutoff, t_missing_cutoff, t_maxMAFLimit, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_max_markers_region, t_outputFile))
}

LDmatRegionInCPP <- function(t_genoType, t_genoIndex_prev, t_genoIndex, annoIndicatorMat, t_outputFile, t_n, t_isImputation, annoStringVec, regionName) {
    invisible(.Call('_SAIGE_LDmatRegionInCPP', PACKAGE = 'SAIGE', t_genoType, t_genoIndex_prev, t_genoIndex, annoIndicatorMat, t_outputFile, t_n, t_isImputation, annoStringVec, regionName))
}

openOutfile_single_LDmat <- function(isappend) {
    .Call('_SAIGE_openOutfile_single_LDmat', PACKAGE = 'SAIGE', isappend)
}

openOutfile_LDmat <- function(isappend) {
    .Call('_SAIGE_openOutfile_LDmat', PACKAGE = 'SAIGE', isappend)
}

openOutfile_index_LDmat <- function(isappend) {
    .Call('_SAIGE_openOutfile_index_LDmat', PACKAGE = 'SAIGE', isappend)
}

closeOutfile_single_LDmat <- function() {
    invisible(.Call('_SAIGE_closeOutfile_single_LDmat', PACKAGE = 'SAIGE'))
}

setAssocTest_GlobalVarsInCPP <- function(t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_dosage_zerod_cutoff, t_dosage_zerod_MAC_cutoff, t_weights_beta, t_outputFilePrefix, t_MACCutoffforER, t_isadmixed) {
    invisible(.Call('_SAIGE_setAssocTest_GlobalVarsInCPP', PACKAGE = 'SAIGE', t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_dosage_zerod_cutoff, t_dosage_zerod_MAC_cutoff, t_weights_beta, t_outputFilePrefix, t_MACCutoffforER, t_isadmixed))
}

setAssocTest_GlobalVarsInCPP_indexInModel_male <- function(t_indexInModel_male) {
    invisible(.Call('_SAIGE_setAssocTest_GlobalVarsInCPP_indexInModel_male', PACKAGE = 'SAIGE', t_indexInModel_male))
}

setAssocTest_GlobalVarsInCPP_X_PARregion_mat <- function(t_X_PARregion_mat) {
    invisible(.Call('_SAIGE_setAssocTest_GlobalVarsInCPP_X_PARregion_mat', PACKAGE = 'SAIGE', t_X_PARregion_mat))
}

setMarker_GlobalVarsInCPP <- function(t_isOutputMoreDetails, t_marker_chunksize) {
    invisible(.Call('_SAIGE_setMarker_GlobalVarsInCPP', PACKAGE = 'SAIGE', t_isOutputMoreDetails, t_marker_chunksize))
}

setRegion_GlobalVarsInCPP <- function(t_max_maf_region, t_max_markers_region, t_MACCutoff_to_CollapseUltraRare, t_min_gourpmac_for_burdenonly, t_r_corr) {
    invisible(.Call('_SAIGE_setRegion_GlobalVarsInCPP', PACKAGE = 'SAIGE', t_max_maf_region, t_max_markers_region, t_MACCutoff_to_CollapseUltraRare, t_min_gourpmac_for_burdenonly, t_r_corr))
}

mainMarkerInCPP <- function(t_genoType, t_traitType, t_genoIndex_prev, t_genoIndex, t_isMoreOutput, t_isImputation, t_isFirth) {
    invisible(.Call('_SAIGE_mainMarkerInCPP', PACKAGE = 'SAIGE', t_genoType, t_traitType, t_genoIndex_prev, t_genoIndex, t_isMoreOutput, t_isImputation, t_isFirth))
}

Unified_getOneMarker <- function(t_genoType, t_gIndex_prev, t_gIndex, t_ref, t_alt, t_marker, t_pd, t_chr, t_altFreq, t_altCounts, t_missingRate, t_imputeInfo, t_isOutputIndexForMissing, t_indexForMissing, t_isOnlyOutputNonZero, t_indexForNonZero, t_GVec, t_isImputation) {
    .Call('_SAIGE_Unified_getOneMarker', PACKAGE = 'SAIGE', t_genoType, t_gIndex_prev, t_gIndex, t_ref, t_alt, t_marker, t_pd, t_chr, t_altFreq, t_altCounts, t_missingRate, t_imputeInfo, t_isOutputIndexForMissing, t_indexForMissing, t_isOnlyOutputNonZero, t_indexForNonZero, t_GVec, t_isImputation)
}

processMale_XnonPAR <- function(t_GVec, t_pd, t_XPARregion) {
    invisible(.Call('_SAIGE_processMale_XnonPAR', PACKAGE = 'SAIGE', t_GVec, t_pd, t_XPARregion))
}

Unified_getSampleSizeinGeno <- function(t_genoType) {
    .Call('_SAIGE_Unified_getSampleSizeinGeno', PACKAGE = 'SAIGE', t_genoType)
}

Unified_getSampleSizeinAnalysis <- function(t_genoType) {
    .Call('_SAIGE_Unified_getSampleSizeinAnalysis', PACKAGE = 'SAIGE', t_genoType)
}

setPLINKobjInCPP <- function(t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder) {
    invisible(.Call('_SAIGE_setPLINKobjInCPP', PACKAGE = 'SAIGE', t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder))
}

setBGENobjInCPP <- function(t_bgenFileName, t_bgenFileIndex, t_SampleInBgen, t_SampleInModel, t_AlleleOrder) {
    invisible(.Call('_SAIGE_setBGENobjInCPP', PACKAGE = 'SAIGE', t_bgenFileName, t_bgenFileIndex, t_SampleInBgen, t_SampleInModel, t_AlleleOrder))
}

setVCFobjInCPP <- function(t_vcfFileName, t_vcfFileIndex, t_vcfField, t_SampleInModel) {
    invisible(.Call('_SAIGE_setVCFobjInCPP', PACKAGE = 'SAIGE', t_vcfFileName, t_vcfFileIndex, t_vcfField, t_SampleInModel))
}

setSAIGEobjInCPP <- function(t_XVX, t_XXVX_inv, t_XV, t_XVX_inv_XV, t_Sigma_iXXSigma_iX, t_X, t_S_a, t_res, t_mu2, t_mu, t_varRatio_sparse, t_varRatio_null, t_cateVarRatioMinMACVecExclude, t_cateVarRatioMaxMACVecInclude, t_SPA_Cutoff, t_tauvec, t_traitType, t_y, t_impute_method, t_flagSparseGRM, t_isFastTest, t_pval_cutoff_for_fastTest, t_locationMat, t_valueVec, t_dimNum, t_isCondition, t_condition_genoIndex, t_is_Firth_beta, t_pCutoffforFirth, t_offset, t_resout) {
    invisible(.Call('_SAIGE_setSAIGEobjInCPP', PACKAGE = 'SAIGE', t_XVX, t_XXVX_inv, t_XV, t_XVX_inv_XV, t_Sigma_iXXSigma_iX, t_X, t_S_a, t_res, t_mu2, t_mu, t_varRatio_sparse, t_varRatio_null, t_cateVarRatioMinMACVecExclude, t_cateVarRatioMaxMACVecInclude, t_SPA_Cutoff, t_tauvec, t_traitType, t_y, t_impute_method, t_flagSparseGRM, t_isFastTest, t_pval_cutoff_for_fastTest, t_locationMat, t_valueVec, t_dimNum, t_isCondition, t_condition_genoIndex, t_is_Firth_beta, t_pCutoffforFirth, t_offset, t_resout))
}

setSparseSigmaInCPP <- function(r, t_locationMatinR, t_valueVecinR) {
    invisible(.Call('_SAIGE_setSparseSigmaInCPP', PACKAGE = 'SAIGE', r, t_locationMatinR, t_valueVecinR))
}

RegionSetUpConditional_binary_InCPP <- function(t_weight_cond) {
    .Call('_SAIGE_RegionSetUpConditional_binary_InCPP', PACKAGE = 'SAIGE', t_weight_cond)
}

mainRegionInCPP <- function(t_genoType, t_genoIndex_prev, t_genoIndex, annoIndicatorMat, maxMAFVec, t_outputFile, t_traitType, t_n, P1Mat, P2Mat, t_regionTestType, t_isImputation, t_weight, t_weight_cond, t_isSingleinGroupTest, t_isOutputMarkerList, annoStringVec, regionName, t_isFastTest, t_isMoreOutput) {
    .Call('_SAIGE_mainRegionInCPP', PACKAGE = 'SAIGE', t_genoType, t_genoIndex_prev, t_genoIndex, annoIndicatorMat, maxMAFVec, t_outputFile, t_traitType, t_n, P1Mat, P2Mat, t_regionTestType, t_isImputation, t_weight, t_weight_cond, t_isSingleinGroupTest, t_isOutputMarkerList, annoStringVec, regionName, t_isFastTest, t_isMoreOutput)
}

assign_conditionMarkers_factors <- function(t_genoType, t_genoIndex_prev, t_genoIndex, t_n, t_weight_cond) {
    invisible(.Call('_SAIGE_assign_conditionMarkers_factors', PACKAGE = 'SAIGE', t_genoType, t_genoIndex_prev, t_genoIndex, t_n, t_weight_cond))
}

assign_conditionMarkers_factors_binary_region <- function(scalefactor_G2_cond) {
    invisible(.Call('_SAIGE_assign_conditionMarkers_factors_binary_region', PACKAGE = 'SAIGE', scalefactor_G2_cond))
}

set_iterator_inVcf <- function(variantList, chrom, beg_pd, end_pd) {
    invisible(.Call('_SAIGE_set_iterator_inVcf', PACKAGE = 'SAIGE', variantList, chrom, beg_pd, end_pd))
}

check_Vcf_end <- function() {
    .Call('_SAIGE_check_Vcf_end', PACKAGE = 'SAIGE')
}

move_forward_iterator_Vcf <- function(i) {
    invisible(.Call('_SAIGE_move_forward_iterator_Vcf', PACKAGE = 'SAIGE', i))
}

fast_logistf_fit <- function(x, y, weight, offset, firth, col_fit, init, maxit, maxstep, maxhs, lconv, gconv, xconv, isfirthconverge) {
    .Call('_SAIGE_fast_logistf_fit', PACKAGE = 'SAIGE', x, y, weight, offset, firth, col_fit, init, maxit, maxstep, maxhs, lconv, gconv, xconv, isfirthconverge)
}

closeGenoFile <- function(t_genoType) {
    invisible(.Call('_SAIGE_closeGenoFile', PACKAGE = 'SAIGE', t_genoType))
}

openOutfile <- function(t_traitType, isappend) {
    .Call('_SAIGE_openOutfile', PACKAGE = 'SAIGE', t_traitType, isappend)
}

openOutfile_singleinGroup <- function(t_traitType, t_isImputation, isappend, t_isMoreOutput) {
    .Call('_SAIGE_openOutfile_singleinGroup', PACKAGE = 'SAIGE', t_traitType, t_isImputation, isappend, t_isMoreOutput)
}

openOutfile_single <- function(t_traitType, t_isImputation, isappend, t_isMoreOutput) {
    .Call('_SAIGE_openOutfile_single', PACKAGE = 'SAIGE', t_traitType, t_isImputation, isappend, t_isMoreOutput)
}

set_flagSparseGRM_cur_SAIGE <- function(t_flagSparseGRM_cur) {
    invisible(.Call('_SAIGE_set_flagSparseGRM_cur_SAIGE', PACKAGE = 'SAIGE', t_flagSparseGRM_cur))
}

set_flagSparseGRM_cur_SAIGE_org <- function() {
    invisible(.Call('_SAIGE_set_flagSparseGRM_cur_SAIGE_org', PACKAGE = 'SAIGE'))
}

copy_singleInGroup <- function() {
    invisible(.Call('_SAIGE_copy_singleInGroup', PACKAGE = 'SAIGE'))
}

mainAdmixedInCPP <- function(RegionList, t_genoType, t_outputFile, t_traitType, t_n, t_regionTestType, t_weight_cond, t_isImputation, t_isFastTest, t_isMoreOutput, t_isWriteHeader) {
    invisible(.Call('_SAIGE_mainAdmixedInCPP', PACKAGE = 'SAIGE', RegionList, t_genoType, t_outputFile, t_traitType, t_n, t_regionTestType, t_weight_cond, t_isImputation, t_isFastTest, t_isMoreOutput, t_isWriteHeader))
}

Unified_getOneMarker_Admixed <- function(t_genoType, t_gIndex_prev, t_gIndex, t_ref, t_alt, t_marker, t_pd, t_chr, t_altFreq, t_altCounts, t_missingRate, t_imputeInfo, t_isOutputIndexForMissing, t_indexForMissing, t_isOnlyOutputNonZero, t_indexForNonZero, t_GVec, t_isImputation, t_vcfField) {
    .Call('_SAIGE_Unified_getOneMarker_Admixed', PACKAGE = 'SAIGE', t_genoType, t_gIndex_prev, t_gIndex, t_ref, t_alt, t_marker, t_pd, t_chr, t_altFreq, t_altCounts, t_missingRate, t_imputeInfo, t_isOutputIndexForMissing, t_indexForMissing, t_isOnlyOutputNonZero, t_indexForNonZero, t_GVec, t_isImputation, t_vcfField)
}

mainMarkerAdmixedInCPP <- function(t_genoType, t_traitType, t_genoIndex_prev, t_genoIndex, t_isMoreOutput, t_isImputation, t_isFirth, t_NumberofANC, t_pvalcutoff_of_haplotype) {
    invisible(.Call('_SAIGE_mainMarkerAdmixedInCPP', PACKAGE = 'SAIGE', t_genoType, t_traitType, t_genoIndex_prev, t_genoIndex, t_isMoreOutput, t_isImputation, t_isFirth, t_NumberofANC, t_pvalcutoff_of_haplotype))
}

openOutfile_single_admixed_new <- function(t_traitType, t_isImputation, isappend, t_isMoreOutput, t_NumberofANC) {
    .Call('_SAIGE_openOutfile_single_admixed_new', PACKAGE = 'SAIGE', t_traitType, t_isImputation, isappend, t_isMoreOutput, t_NumberofANC)
}

process_Haplotype_Region <- function(t_traitType, t_genoType, t_n, t_NumberofANC, t_genoIndex_prev, t_genoIndex) {
    .Call('_SAIGE_process_Haplotype_Region', PACKAGE = 'SAIGE', t_traitType, t_genoType, t_n, t_NumberofANC, t_genoIndex_prev, t_genoIndex)
}

set_current_anc_index_name <- function(anc_index_name) {
    invisible(.Call('_SAIGE_set_current_anc_index_name', PACKAGE = 'SAIGE', anc_index_name))
}

closeGenoFile_plink <- function() {
    invisible(.Call('_SAIGE_closeGenoFile_plink', PACKAGE = 'SAIGE'))
}

gettotalMarker <- function() {
    .Call('_SAIGE_gettotalMarker', PACKAGE = 'SAIGE')
}

getAlleleFreqVec <- function() {
    .Call('_SAIGE_getAlleleFreqVec', PACKAGE = 'SAIGE')
}

getMACVec <- function() {
    .Call('_SAIGE_getMACVec', PACKAGE = 'SAIGE')
}

getMACVec_forVarRatio <- function() {
    .Call('_SAIGE_getMACVec_forVarRatio', PACKAGE = 'SAIGE')
}

getIndexVec_forVarRatio <- function() {
    .Call('_SAIGE_getIndexVec_forVarRatio', PACKAGE = 'SAIGE')
}

getIsVarRatioGeno <- function() {
    .Call('_SAIGE_getIsVarRatioGeno', PACKAGE = 'SAIGE')
}

getSubMarkerIndex <- function() {
    .Call('_SAIGE_getSubMarkerIndex', PACKAGE = 'SAIGE')
}

getQCdMarkerIndex <- function() {
    .Call('_SAIGE_getQCdMarkerIndex', PACKAGE = 'SAIGE')
}

getSubMarkerNum <- function() {
    .Call('_SAIGE_getSubMarkerNum', PACKAGE = 'SAIGE')
}

getNnomissingOut <- function() {
    .Call('_SAIGE_getNnomissingOut', PACKAGE = 'SAIGE')
}

getMsub_MAFge_minMAFtoConstructGRM <- function() {
    .Call('_SAIGE_getMsub_MAFge_minMAFtoConstructGRM', PACKAGE = 'SAIGE')
}

getMsub_MAFge_minMAFtoConstructGRM_singleChr <- function() {
    .Call('_SAIGE_getMsub_MAFge_minMAFtoConstructGRM_singleChr', PACKAGE = 'SAIGE')
}

Get_MultiMarkersBySample_StdGeno_Mat <- function() {
    invisible(.Call('_SAIGE_Get_MultiMarkersBySample_StdGeno_Mat', PACKAGE = 'SAIGE'))
}

Get_MultiMarkersBySample_StdGeno <- function(markerIndexVec, stdGenoMultiMarkers) {
    invisible(.Call('_SAIGE_Get_MultiMarkersBySample_StdGeno', PACKAGE = 'SAIGE', markerIndexVec, stdGenoMultiMarkers))
}

parallelCrossProd <- function(bVec) {
    .Call('_SAIGE_parallelCrossProd', PACKAGE = 'SAIGE', bVec)
}

innerProductFun <- function(x, y) {
    .Call('_SAIGE_innerProductFun', PACKAGE = 'SAIGE', x, y)
}

parallelCrossProd_full <- function(bVec, markerNum) {
    .Call('_SAIGE_parallelCrossProd_full', PACKAGE = 'SAIGE', bVec, markerNum)
}

parallelCrossProd_LOCO <- function(bVec) {
    .Call('_SAIGE_parallelCrossProd_LOCO', PACKAGE = 'SAIGE', bVec)
}

setupSparseGRM <- function(r, locationMatinR, valueVecinR) {
    invisible(.Call('_SAIGE_setupSparseGRM', PACKAGE = 'SAIGE', r, locationMatinR, valueVecinR))
}

getCrossprodMatAndKin <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin', PACKAGE = 'SAIGE', bVec)
}

getCrossprodMatAndKin_LOCO <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin_LOCO', PACKAGE = 'SAIGE', bVec)
}

printComb <- function(N) {
    invisible(.Call('_SAIGE_printComb', PACKAGE = 'SAIGE', N))
}

findIndiceRelatedSample <- function() {
    invisible(.Call('_SAIGE_findIndiceRelatedSample', PACKAGE = 'SAIGE'))
}

parallelcalsparseGRM <- function(GRMvec) {
    invisible(.Call('_SAIGE_parallelcalsparseGRM', PACKAGE = 'SAIGE', GRMvec))
}

parallelsumTwoVec <- function(x) {
    invisible(.Call('_SAIGE_parallelsumTwoVec', PACKAGE = 'SAIGE', x))
}

setgeno <- function(bedfile, bimfile, famfile, subSampleInGeno, indicatorGenoSamplesWithPheno, memoryChunk, isDiagofKinSetAsOne) {
    invisible(.Call('_SAIGE_setgeno', PACKAGE = 'SAIGE', bedfile, bimfile, famfile, subSampleInGeno, indicatorGenoSamplesWithPheno, memoryChunk, isDiagofKinSetAsOne))
}

Get_OneSNP_Geno <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_Geno', PACKAGE = 'SAIGE', SNPIdx)
}

Get_OneSNP_Geno_forVarRatio <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_Geno_forVarRatio', PACKAGE = 'SAIGE', SNPIdx)
}

Get_OneSNP_StdGeno <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_StdGeno', PACKAGE = 'SAIGE', SNPIdx)
}

getDiagOfSigma <- function(wVec, tauVec) {
    .Call('_SAIGE_getDiagOfSigma', PACKAGE = 'SAIGE', wVec, tauVec)
}

getDiagOfSigma_LOCO <- function(wVec, tauVec) {
    .Call('_SAIGE_getDiagOfSigma_LOCO', PACKAGE = 'SAIGE', wVec, tauVec)
}

getDiagOfSigma_surv <- function(diagofWminusUinv, tauVec) {
    .Call('_SAIGE_getDiagOfSigma_surv', PACKAGE = 'SAIGE', diagofWminusUinv, tauVec)
}

getDiagOfSigma_surv_LOCO <- function(diagofWminusUinv, tauVec) {
    .Call('_SAIGE_getDiagOfSigma_surv_LOCO', PACKAGE = 'SAIGE', diagofWminusUinv, tauVec)
}

getCrossprod <- function(bVec, wVec, tauVec) {
    .Call('_SAIGE_getCrossprod', PACKAGE = 'SAIGE', bVec, wVec, tauVec)
}

getCrossprod_LOCO <- function(bVec, wVec, tauVec) {
    .Call('_SAIGE_getCrossprod_LOCO', PACKAGE = 'SAIGE', bVec, wVec, tauVec)
}

extractVecatTimek <- function(ktime, rvecIndex, winvn) {
    .Call('_SAIGE_extractVecatTimek', PACKAGE = 'SAIGE', ktime, rvecIndex, winvn)
}

extractUvecforkthTime <- function(kthtime, RvecIndex, NVec, sqrtDVec, kthVec) {
    invisible(.Call('_SAIGE_extractUvecforkthTime', PACKAGE = 'SAIGE', kthtime, RvecIndex, NVec, sqrtDVec, kthVec))
}

parallelCrossProd_UandbVec_surv <- function(bVec, RvecIndex, NVec, sqrtDVec) {
    .Call('_SAIGE_parallelCrossProd_UandbVec_surv', PACKAGE = 'SAIGE', bVec, RvecIndex, NVec, sqrtDVec)
}

getProdWminusUb_Surv <- function(bVec, RvecIndex, NVec, sqrtDVec, wVec) {
    .Call('_SAIGE_getProdWminusUb_Surv', PACKAGE = 'SAIGE', bVec, RvecIndex, NVec, sqrtDVec, wVec)
}

getCrossprod_Surv <- function(bVec, wVec, tauVec, WinvNRt, ACinv) {
    .Call('_SAIGE_getCrossprod_Surv', PACKAGE = 'SAIGE', bVec, wVec, tauVec, WinvNRt, ACinv)
}

getCrossprod_Surv_LOCO <- function(bVec, wVec, tauVec, WinvNRt, ACinv) {
    .Call('_SAIGE_getCrossprod_Surv_LOCO', PACKAGE = 'SAIGE', bVec, wVec, tauVec, WinvNRt, ACinv)
}

extractVecfornthSample <- function(nthsample, k_uniqTime, RvecIndex, sqrtWinvNVec, nthVec) {
    invisible(.Call('_SAIGE_extractVecfornthSample', PACKAGE = 'SAIGE', nthsample, k_uniqTime, RvecIndex, sqrtWinvNVec, nthVec))
}

extractVecfornthSample_double <- function(nthsample, k_uniqTime, RvecIndex, sqrtWinvNVec, nthVec) {
    invisible(.Call('_SAIGE_extractVecfornthSample_double', PACKAGE = 'SAIGE', nthsample, k_uniqTime, RvecIndex, sqrtWinvNVec, nthVec))
}

parallelCrossProd_AandbVec_surv <- function(bVec, RvecIndex, sqrtWinvNVec, kuniqtime) {
    .Call('_SAIGE_parallelCrossProd_AandbVec_surv', PACKAGE = 'SAIGE', bVec, RvecIndex, sqrtWinvNVec, kuniqtime)
}

parallelCrossProd_AandbVec_surv_double <- function(bVec, RvecIndex, sqrtWinvNVec, kuniqtime) {
    .Call('_SAIGE_parallelCrossProd_AandbVec_surv_double', PACKAGE = 'SAIGE', bVec, RvecIndex, sqrtWinvNVec, kuniqtime)
}

parallelCrossProd_RandbVec_surv <- function(bVec, RvecIndex, kuniqtime) {
    .Call('_SAIGE_parallelCrossProd_RandbVec_surv', PACKAGE = 'SAIGE', bVec, RvecIndex, kuniqtime)
}

getProdRb_Surv <- function(bVec, RvecIndex, kuniqtime) {
    .Call('_SAIGE_getProdRb_Surv', PACKAGE = 'SAIGE', bVec, RvecIndex, kuniqtime)
}

getProdAb_Surv <- function(bVec, RvecIndex, sqrtWinvNVec, Dvec) {
    .Call('_SAIGE_getProdAb_Surv', PACKAGE = 'SAIGE', bVec, RvecIndex, sqrtWinvNVec, Dvec)
}

getProdAb_Surv_double <- function(bVec, RvecIndex, sqrtWinvNVec, Dvec) {
    .Call('_SAIGE_getProdAb_Surv_double', PACKAGE = 'SAIGE', bVec, RvecIndex, sqrtWinvNVec, Dvec)
}

getDiagofA <- function(RvecIndex, sqrtWinvNVec, Dvec) {
    .Call('_SAIGE_getDiagofA', PACKAGE = 'SAIGE', RvecIndex, sqrtWinvNVec, Dvec)
}

getDiagofA_double <- function(RvecIndex, sqrtWinvNVec, Dvec) {
    .Call('_SAIGE_getDiagofA_double', PACKAGE = 'SAIGE', RvecIndex, sqrtWinvNVec, Dvec)
}

getPCG1ofACinvAndVector_test <- function(bVec, RvecIndex, sqrtWinvNVec, Dvec, maxiterPCG, tolPCG, wVec, tauVec, Rmat) {
    .Call('_SAIGE_getPCG1ofACinvAndVector_test', PACKAGE = 'SAIGE', bVec, RvecIndex, sqrtWinvNVec, Dvec, maxiterPCG, tolPCG, wVec, tauVec, Rmat)
}

getPCG1ofACinvAndVector <- function(bVec, RvecIndex, sqrtWinvNVec, Dvec, maxiterPCG, tolPCG, wVec, tauVec) {
    .Call('_SAIGE_getPCG1ofACinvAndVector', PACKAGE = 'SAIGE', bVec, RvecIndex, sqrtWinvNVec, Dvec, maxiterPCG, tolPCG, wVec, tauVec)
}

getProdRtb_Surv <- function(bVec, RvecIndex) {
    .Call('_SAIGE_getProdRtb_Surv', PACKAGE = 'SAIGE', bVec, RvecIndex)
}

getCrossprod_Surv_new <- function(bVec, wVec, tauVec, RvecIndex, sqrtWinvNVec, NWinv, Dvec, kuniqtime, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getCrossprod_Surv_new', PACKAGE = 'SAIGE', bVec, wVec, tauVec, RvecIndex, sqrtWinvNVec, NWinv, Dvec, kuniqtime, maxiterPCG, tolPCG)
}

getPCG1ofWminusUAndVector <- function(wVec, tauVec, bVec, RvecIndex, NVec, sqrtDVec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getPCG1ofWminusUAndVector', PACKAGE = 'SAIGE', wVec, tauVec, bVec, RvecIndex, NVec, sqrtDVec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG, dofWminusU)
}

getCrossprod_Surv_new2 <- function(bVec, wVec, tauVec, RvecIndex, NVec, sqrtDVec, diagofWminusUinv, kuniqtime, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getCrossprod_Surv_new2', PACKAGE = 'SAIGE', bVec, wVec, tauVec, RvecIndex, NVec, sqrtDVec, diagofWminusUinv, kuniqtime, maxiterPCG, tolPCG, dofWminusU)
}

getCrossprod_Surv_new2_LOCO <- function(bVec, wVec, tauVec, RvecIndex, NVec, sqrtDVec, diagofWminusUinv, kuniqtime, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getCrossprod_Surv_new2_LOCO', PACKAGE = 'SAIGE', bVec, wVec, tauVec, RvecIndex, NVec, sqrtDVec, diagofWminusUinv, kuniqtime, maxiterPCG, tolPCG, dofWminusU)
}

getCrossprod_Surv_new_LOCO <- function(bVec, wVec, tauVec, RvecIndex, sqrtWinvNVec, NWinv, Dvec, kuniqtime, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getCrossprod_Surv_new_LOCO', PACKAGE = 'SAIGE', bVec, wVec, tauVec, RvecIndex, sqrtWinvNVec, NWinv, Dvec, kuniqtime, maxiterPCG, tolPCG)
}

gen_sp_GRM <- function() {
    .Call('_SAIGE_gen_sp_GRM', PACKAGE = 'SAIGE')
}

gen_sp_Sigma <- function(wVec, tauVec) {
    .Call('_SAIGE_gen_sp_Sigma', PACKAGE = 'SAIGE', wVec, tauVec)
}

gen_spsolve_v3 <- function(yvec) {
    .Call('_SAIGE_gen_spsolve_v3', PACKAGE = 'SAIGE', yvec)
}

gen_spsolve_v4 <- function(wVec, tauVec, yvec) {
    .Call('_SAIGE_gen_spsolve_v4', PACKAGE = 'SAIGE', wVec, tauVec, yvec)
}

setisUsePrecondM <- function(isUseSparseSigmaforPCG) {
    invisible(.Call('_SAIGE_setisUsePrecondM', PACKAGE = 'SAIGE', isUseSparseSigmaforPCG))
}

setisUseSparseSigmaforInitTau <- function(isUseSparseSigmaforInitTau0) {
    invisible(.Call('_SAIGE_setisUseSparseSigmaforInitTau', PACKAGE = 'SAIGE', isUseSparseSigmaforInitTau0))
}

setisUseSparseSigmaforNullModelFitting <- function(isUseSparseSigmaforModelFitting0) {
    invisible(.Call('_SAIGE_setisUseSparseSigmaforNullModelFitting', PACKAGE = 'SAIGE', isUseSparseSigmaforModelFitting0))
}

setisUsePCGwithSparseSigma <- function(isUsePCGwithSparseSigma0) {
    invisible(.Call('_SAIGE_setisUsePCGwithSparseSigma', PACKAGE = 'SAIGE', isUsePCGwithSparseSigma0))
}

getPCG1ofSigmaAndVector <- function(wVec, tauVec, bVec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector', PACKAGE = 'SAIGE', wVec, tauVec, bVec, maxiterPCG, tolPCG)
}

getPCG1ofSigmaAndVector_Surv <- function(wVec, tauVec, bVec, WinvNRt, ACinv, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_Surv', PACKAGE = 'SAIGE', wVec, tauVec, bVec, WinvNRt, ACinv, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG)
}

getPCG1ofSigmaAndVector_old <- function(wVec, tauVec, bVec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_old', PACKAGE = 'SAIGE', wVec, tauVec, bVec, maxiterPCG, tolPCG)
}

getPCG1ofSigmaAndVector_Surv_LOCO <- function(wVec, tauVec, bVec, WinvNRt, ACinv, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_Surv_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, bVec, WinvNRt, ACinv, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG)
}

getPCG1ofSigmaAndVector_Surv_new <- function(wVec, tauVec, bVec, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_Surv_new', PACKAGE = 'SAIGE', wVec, tauVec, bVec, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG)
}

getPCG1ofSigmaAndVector_Surv_new2 <- function(wVec, tauVec, bVec, RvecIndex, NVec, sqrtDvec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_Surv_new2', PACKAGE = 'SAIGE', wVec, tauVec, bVec, RvecIndex, NVec, sqrtDvec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG, dofWminusU)
}

getPCG1ofSigmaAndVector_Surv_LOCO_new2 <- function(wVec, tauVec, bVec, RvecIndex, NVec, sqrtDvec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_Surv_LOCO_new2', PACKAGE = 'SAIGE', wVec, tauVec, bVec, RvecIndex, NVec, sqrtDvec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG, dofWminusU)
}

getPCG1ofSigmaAndVector_Surv_new_LOCO <- function(wVec, tauVec, bVec, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_Surv_new_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, bVec, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, x0Vec, maxiterPCG, tolPCG)
}

getPCG1ofSigmaAndVector_LOCO <- function(wVec, tauVec, bVec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, bVec, maxiterPCG, tolPCG)
}

set_seed <- function(seed) {
    invisible(.Call('_SAIGE_set_seed', PACKAGE = 'SAIGE', seed))
}

nb <- function(n) {
    .Call('_SAIGE_nb', PACKAGE = 'SAIGE', n)
}

setStartEndIndex <- function(startIndex, endIndex, chromIndex) {
    invisible(.Call('_SAIGE_setStartEndIndex', PACKAGE = 'SAIGE', startIndex, endIndex, chromIndex))
}

setStartEndIndexVec <- function(startIndex_vec, endIndex_vec) {
    invisible(.Call('_SAIGE_setStartEndIndexVec', PACKAGE = 'SAIGE', startIndex_vec, endIndex_vec))
}

calCV <- function(xVec) {
    .Call('_SAIGE_calCV', PACKAGE = 'SAIGE', xVec)
}

GetTrace <- function(Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call('_SAIGE_GetTrace', PACKAGE = 'SAIGE', Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

getCoefficients <- function(Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getCoefficients', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG)
}

getCoefficients_LOCO <- function(Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getCoefficients_LOCO', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG)
}

getCoefficients_q_LOCO <- function(Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getCoefficients_q_LOCO', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG)
}

getAIScore <- function(Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call('_SAIGE_getAIScore', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

fitglmmaiRPCG <- function(Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff) {
    .Call('_SAIGE_fitglmmaiRPCG', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff)
}

getSigma_X <- function(wVec, tauVec, Xmat, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_X', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, maxiterPCG, tolPCG)
}

getSigma_X_LOCO <- function(wVec, tauVec, Xmat, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_X_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, maxiterPCG, tolPCG)
}

getSigma_X_Surv <- function(wVec, tauVec, Xmat, WinvNRt, ACinv, diagofWminusUinv, sqrtDRN, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_X_Surv', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, WinvNRt, ACinv, diagofWminusUinv, sqrtDRN, maxiterPCG, tolPCG)
}

getSigma_X_Surv_LOCO <- function(wVec, tauVec, Xmat, WinvNRt, ACinv, diagofWminusUinv, sqrtDRN, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_X_Surv_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, WinvNRt, ACinv, diagofWminusUinv, sqrtDRN, maxiterPCG, tolPCG)
}

getSigma_X_Surv_new <- function(wVec, tauVec, Xmat, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_X_Surv_new', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG)
}

getSigma_X_Surv_new_LOCO <- function(wVec, tauVec, Xmat, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_X_Surv_new_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG)
}

getSigma_X_Surv_new2 <- function(wVec, tauVec, Xmat, RvecIndex, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getSigma_X_Surv_new2', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, RvecIndex, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG, dofWminusU)
}

getSigma_X_Surv_new2_LOCO <- function(wVec, tauVec, Xmat, RvecIndex, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getSigma_X_Surv_new2_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, RvecIndex, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG, dofWminusU)
}

getSigma_G <- function(wVec, tauVec, Gvec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_G', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, maxiterPCG, tolPCG)
}

getSigma_G_LOCO <- function(wVec, tauVec, Gvec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_G_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, maxiterPCG, tolPCG)
}

getSigma_G_Surv <- function(wVec, tauVec, Gvec, WinvNRt, ACinv, diagofWminusUinv, sqrtDRN, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_G_Surv', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, WinvNRt, ACinv, diagofWminusUinv, sqrtDRN, maxiterPCG, tolPCG)
}

getSigma_G_Surv_LOCO <- function(wVec, tauVec, Gvec, WinvNRt, ACinv, diagofWminusUinv, sqrtDRN, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_G_Surv_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, WinvNRt, ACinv, diagofWminusUinv, sqrtDRN, maxiterPCG, tolPCG)
}

getSigma_G_Surv_new <- function(wVec, tauVec, Gvec, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_G_Surv_new', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG)
}

getSigma_G_Surv_new2 <- function(wVec, tauVec, Gvec, RvecIndex, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getSigma_G_Surv_new2', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, RvecIndex, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG, dofWminusU)
}

getSigma_G_Surv_new2_LOCO <- function(wVec, tauVec, Gvec, RvecIndex, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG, dofWminusU) {
    .Call('_SAIGE_getSigma_G_Surv_new2_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, RvecIndex, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG, dofWminusU)
}

getSigma_G_Surv_new_LOCO <- function(wVec, tauVec, Gvec, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_G_Surv_new_LOCO', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, RvecIndex, sqrtWinvNVec, WinvN, Dvec, diagofWminusUinv, Nvec, maxiterPCG, tolPCG)
}

GetTrace_q <- function(Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call('_SAIGE_GetTrace_q', PACKAGE = 'SAIGE', Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

getAIScore_q <- function(Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call('_SAIGE_getAIScore_q', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

getAIScore_q_LOCO <- function(Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call('_SAIGE_getAIScore_q_LOCO', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

fitglmmaiRPCG_q_LOCO <- function(Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff) {
    .Call('_SAIGE_fitglmmaiRPCG_q_LOCO', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff)
}

fitglmmaiRPCG_q <- function(Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff) {
    .Call('_SAIGE_fitglmmaiRPCG_q', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff)
}

parallelCrossProd_usingSubMarker <- function(bVec) {
    .Call('_SAIGE_parallelCrossProd_usingSubMarker', PACKAGE = 'SAIGE', bVec)
}

getCrossprodMatAndKin_usingSubMarker <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin_usingSubMarker', PACKAGE = 'SAIGE', bVec)
}

parallelInnerProduct <- function(x, y) {
    .Call('_SAIGE_parallelInnerProduct', PACKAGE = 'SAIGE', x, y)
}

calGRMValueforSamplePair <- function(sampleidsVec) {
    .Call('_SAIGE_calGRMValueforSamplePair', PACKAGE = 'SAIGE', sampleidsVec)
}

createSparseKin <- function(markerIndexVec, relatednessCutoff, wVec, tauVec) {
    .Call('_SAIGE_createSparseKin', PACKAGE = 'SAIGE', markerIndexVec, relatednessCutoff, wVec, tauVec)
}

getColfromStdGenoMultiMarkersMat <- function(a) {
    .Call('_SAIGE_getColfromStdGenoMultiMarkersMat', PACKAGE = 'SAIGE', a)
}

getNColStdGenoMultiMarkersMat <- function() {
    .Call('_SAIGE_getNColStdGenoMultiMarkersMat', PACKAGE = 'SAIGE')
}

getNRowStdGenoMultiMarkersMat <- function() {
    .Call('_SAIGE_getNRowStdGenoMultiMarkersMat', PACKAGE = 'SAIGE')
}

setSubMarkerIndex <- function(subMarkerIndexRandom) {
    invisible(.Call('_SAIGE_setSubMarkerIndex', PACKAGE = 'SAIGE', subMarkerIndexRandom))
}

setRelatednessCutoff <- function(a) {
    invisible(.Call('_SAIGE_setRelatednessCutoff', PACKAGE = 'SAIGE', a))
}

innerProduct <- function(x, y) {
    .Call('_SAIGE_innerProduct', PACKAGE = 'SAIGE', x, y)
}

refineKin <- function(relatednessCutoff) {
    .Call('_SAIGE_refineKin', PACKAGE = 'SAIGE', relatednessCutoff)
}

shortenList <- function(iMat, kinValueVecTemp, relatednessCutoff, wVec, tauVec) {
    .Call('_SAIGE_shortenList', PACKAGE = 'SAIGE', iMat, kinValueVecTemp, relatednessCutoff, wVec, tauVec)
}

testTime <- function(i, m_bVec) {
    .Call('_SAIGE_testTime', PACKAGE = 'SAIGE', i, m_bVec)
}

gen_sp_v2 <- function(a) {
    .Call('_SAIGE_gen_sp_v2', PACKAGE = 'SAIGE', a)
}

gen_spsolve_v2 <- function(a) {
    .Call('_SAIGE_gen_spsolve_v2', PACKAGE = 'SAIGE', a)
}

gen_spsolve_inR <- function(a, y) {
    .Call('_SAIGE_gen_spsolve_inR', PACKAGE = 'SAIGE', a, y)
}

get_DiagofKin <- function() {
    .Call('_SAIGE_get_DiagofKin', PACKAGE = 'SAIGE')
}

getstdgenoVectorScalorProduct <- function(jth, y, prodVec) {
    invisible(.Call('_SAIGE_getstdgenoVectorScalorProduct', PACKAGE = 'SAIGE', jth, y, prodVec))
}

sumPz <- function(Pbvec, Ubvec, mmchunksize) {
    invisible(.Call('_SAIGE_sumPz', PACKAGE = 'SAIGE', Pbvec, Ubvec, mmchunksize))
}

mmGetPb_MbyN <- function(cthchunk, mmchunksize, bvec, Pbvec, kinbvec) {
    invisible(.Call('_SAIGE_mmGetPb_MbyN', PACKAGE = 'SAIGE', cthchunk, mmchunksize, bvec, Pbvec, kinbvec))
}

mmGetPb_NbyM <- function(cthchunk, mmchunksize, bvec, Pbvec) {
    invisible(.Call('_SAIGE_mmGetPb_NbyM', PACKAGE = 'SAIGE', cthchunk, mmchunksize, bvec, Pbvec))
}

muliplyMailman <- function(bvec, Gbvec, kinbvec) {
    invisible(.Call('_SAIGE_muliplyMailman', PACKAGE = 'SAIGE', bvec, Gbvec, kinbvec))
}

muliplyMailman_NbyM <- function(bvec, tGbvec) {
    invisible(.Call('_SAIGE_muliplyMailman_NbyM', PACKAGE = 'SAIGE', bvec, tGbvec))
}

freqOverStd <- function(freqOverStdVec) {
    invisible(.Call('_SAIGE_freqOverStd', PACKAGE = 'SAIGE', freqOverStdVec))
}

getCrossprodMatAndKin_mailman <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin_mailman', PACKAGE = 'SAIGE', bVec)
}

get_GRMdiagVec <- function() {
    .Call('_SAIGE_get_GRMdiagVec', PACKAGE = 'SAIGE')
}

setminMAFforGRM <- function(minMAFforGRM) {
    invisible(.Call('_SAIGE_setminMAFforGRM', PACKAGE = 'SAIGE', minMAFforGRM))
}

setmaxMissingRateforGRM <- function(maxMissingforGRM) {
    invisible(.Call('_SAIGE_setmaxMissingRateforGRM', PACKAGE = 'SAIGE', maxMissingforGRM))
}

set_Diagof_StdGeno_LOCO <- function() {
    invisible(.Call('_SAIGE_set_Diagof_StdGeno_LOCO', PACKAGE = 'SAIGE'))
}

setminMAC_VarianceRatio <- function(t_minMACVarRatio, t_maxMACVarRatio, t_isVarianceRatioinGeno) {
    invisible(.Call('_SAIGE_setminMAC_VarianceRatio', PACKAGE = 'SAIGE', t_minMACVarRatio, t_maxMACVarRatio, t_isVarianceRatioinGeno))
}

call_qfc <- function(lambdas, noncentral, df, r, sigma, q, lim, acc) {
    .Call('_SAIGE_call_qfc', PACKAGE = 'SAIGE', lambdas, noncentral, df, r, sigma, q, lim, acc)
}

Get_Davies_PVal <- function(Q, W, Q_resampling, isFast) {
    .Call('_SAIGE_Get_Davies_PVal', PACKAGE = 'SAIGE', Q, W, Q_resampling, isFast)
}

SKAT_davies <- function(q, lambda, h, delta, sigma, lim, acc) {
    .Call('_SAIGE_SKAT_davies', PACKAGE = 'SAIGE', q, lambda, h, delta, sigma, lim, acc)
}

SKAT_Optimal_Integrate_Func_Davies <- function(x, pmin_q, param_m, r_all) {
    .Call('_SAIGE_SKAT_Optimal_Integrate_Func_Davies', PACKAGE = 'SAIGE', x, pmin_q, param_m, r_all)
}

Met_SKAT_Get_Pvalue <- function(Score, Phi, r_corr, method, isFast) {
    .Call('_SAIGE_Met_SKAT_Get_Pvalue', PACKAGE = 'SAIGE', Score, Phi, r_corr, method, isFast)
}

Get_Liu_Params <- function(c1) {
    .Call('_SAIGE_Get_Liu_Params', PACKAGE = 'SAIGE', c1)
}

Get_Liu_PVal <- function(Q, W, Q_resampling) {
    .Call('_SAIGE_Get_Liu_PVal', PACKAGE = 'SAIGE', Q, W, Q_resampling)
}

forceSymmetric <- function(K) {
    .Call('_SAIGE_forceSymmetric', PACKAGE = 'SAIGE', K)
}

get_SKAT_pvalue_cpp <- function(Score, Phi, r_corr, Pvalue_SKATO, Pvalue_Burden, Pvalue_SKAT, BETA_Burden, SE_Burden, error_code) {
    invisible(.Call('_SAIGE_get_SKAT_pvalue_cpp', PACKAGE = 'SAIGE', Score, Phi, r_corr, Pvalue_SKATO, Pvalue_Burden, Pvalue_SKAT, BETA_Burden, SE_Burden, error_code))
}

get_jointScore_pvalue <- function(Score, Phi) {
    .Call('_SAIGE_get_jointScore_pvalue', PACKAGE = 'SAIGE', Score, Phi)
}

SPA_ER_kernel_related_Phiadj_fast_new_cpp <- function(p_new, Score, Phi, p_value_burden, regionTestType, scaleFactor) {
    invisible(.Call('_SAIGE_SPA_ER_kernel_related_Phiadj_fast_new_cpp', PACKAGE = 'SAIGE', p_new, Score, Phi, p_value_burden, regionTestType, scaleFactor))
}

get_newPhi_scaleFactor_cpp <- function(q_sum, mu_a, g_sum, p_new, Score, Phi, regionTestType, scaleFactor) {
    invisible(.Call('_SAIGE_get_newPhi_scaleFactor_cpp', PACKAGE = 'SAIGE', q_sum, mu_a, g_sum, p_new, Score, Phi, regionTestType, scaleFactor))
}

SPA <- function(mu, g, q, qinv, pval_noadj, tol, logp, traitType, pval, isSPAConverge) {
    invisible(.Call('_SAIGE_SPA', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp, traitType, pval, isSPAConverge))
}

SPA_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, traitType, pval, isSPAConverge) {
    invisible(.Call('_SAIGE_SPA_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, traitType, pval, isSPAConverge))
}

SPA_pval <- function(mu, g, q, qinv, pval_noadj, tol, logp, traitType, isSPAConverge) {
    .Call('_SAIGE_SPA_pval', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp, traitType, isSPAConverge)
}

Korg_Binom <- function(t1, mu, g) {
    .Call('_SAIGE_Korg_Binom', PACKAGE = 'SAIGE', t1, mu, g)
}

K1_adj_Binom <- function(t1, mu, g, q) {
    .Call('_SAIGE_K1_adj_Binom', PACKAGE = 'SAIGE', t1, mu, g, q)
}

K2_Binom <- function(t1, mu, g) {
    .Call('_SAIGE_K2_Binom', PACKAGE = 'SAIGE', t1, mu, g)
}

getroot_K1_Binom <- function(init, mu, g, q, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_Binom', PACKAGE = 'SAIGE', init, mu, g, q, tol, maxiter)
}

Get_Saddle_Prob_Binom <- function(zeta, mu, g, q, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_Binom', PACKAGE = 'SAIGE', zeta, mu, g, q, logp)
}

SPA_binary <- function(mu, g, q, qinv, pval_noadj, tol, logp) {
    .Call('_SAIGE_SPA_binary', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp)
}

Korg_fast_Binom <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_Korg_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K1_adj_fast_Binom <- function(t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K1_adj_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K2_fast_Binom <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K2_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

getroot_K1_fast_Binom <- function(init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_fast_Binom', PACKAGE = 'SAIGE', init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter)
}

Get_Saddle_Prob_fast_Binom <- function(zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_fast_Binom', PACKAGE = 'SAIGE', zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp)
}

SPA_binary_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol) {
    .Call('_SAIGE_SPA_binary_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol)
}

Korg_Poi <- function(t1, mu, g) {
    .Call('_SAIGE_Korg_Poi', PACKAGE = 'SAIGE', t1, mu, g)
}

K1_adj_Poi <- function(t1, mu, g, q) {
    .Call('_SAIGE_K1_adj_Poi', PACKAGE = 'SAIGE', t1, mu, g, q)
}

K2_Poi <- function(t1, mu, g) {
    .Call('_SAIGE_K2_Poi', PACKAGE = 'SAIGE', t1, mu, g)
}

getroot_K1_Poi <- function(init, mu, g, q, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_Poi', PACKAGE = 'SAIGE', init, mu, g, q, tol, maxiter)
}

Get_Saddle_Prob_Poi <- function(zeta, mu, g, q, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_Poi', PACKAGE = 'SAIGE', zeta, mu, g, q, logp)
}

SPA_survival <- function(mu, g, q, qinv, pval_noadj, tol, logp) {
    .Call('_SAIGE_SPA_survival', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp)
}

Korg_fast_Poi <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_Korg_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K1_adj_fast_Poi <- function(t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K1_adj_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K2_fast_Poi <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K2_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

getroot_K1_fast_Poi <- function(init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_fast_Poi', PACKAGE = 'SAIGE', init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter)
}

Get_Saddle_Prob_fast_Poi <- function(zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_fast_Poi', PACKAGE = 'SAIGE', zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp)
}

SPA_survival_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol) {
    .Call('_SAIGE_SPA_survival_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol)
}

sum_arma1 <- function(X) {
    .Call('_SAIGE_sum_arma1', PACKAGE = 'SAIGE', X)
}

add_logp <- function(p1, p2) {
    .Call('_SAIGE_add_logp', PACKAGE = 'SAIGE', p1, p2)
}

mult_sp_sp_to_sp <- function(a, b) {
    .Call('_SAIGE_mult_sp_sp_to_sp', PACKAGE = 'SAIGE', a, b)
}

mult_sp_den_to_sp <- function(a, b) {
    .Call('_SAIGE_mult_sp_den_to_sp', PACKAGE = 'SAIGE', a, b)
}

mult_den_sp_to_sp <- function(a, b) {
    .Call('_SAIGE_mult_den_sp_to_sp', PACKAGE = 'SAIGE', a, b)
}

gen_sp <- function(a) {
    .Call('_SAIGE_gen_sp', PACKAGE = 'SAIGE', a)
}

